# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

# Site settings:
title: Pizza De Dados
lang: pt-br
permalink: /:title/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
paginate_path: "page:num"


disqus: pizzadedados
# google_analytics: UA-106178084-2

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Pizza de Dados

description: >
    Pizza de Dados podcast, um podcast onde pessoas comuns discutem ciência de dados
author:
  name: Leticia Portella, Jessica Temporal, Gustavo Coelho
  email: pizzadedados@gmail.com
  twitter: pizzadedados
  bio: O podcast Brasileiro sobre Ciêcia de Dados
  email_md5: 01ba6ff2d34a7ee2657ccc9b16014ed4
  facebook: pizzadedados
  youtube: pizzadedados

rss_path: feed.xml
assine_path: assine
pizzaiolos_path: pizzaiolos
sobre_path: sobre

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1
# pizzaiolos photo
lele_photo: "https://i.imgur.com/nXuylsx.jpg"
jess_photo: "https://pbs.twimg.com/profile_images/950517230038548480/3LLLh6G5_400x400.jpg"
gust_photo: "https://pbs.twimg.com/profile_images/927578792419356672/Xs18O64r_400x400.jpg"

BASE_PATH: "https://pizzadedados.com"
image-url: "https://pizzadedados.com/assets/media/avatar.large.png"
url: "https://pizzadedados.com"

plugins:
  - jekyll-paginate

exclude: ["README.md"] # files to exclude
